#!/bin/bash

sed -i 's#// Generated by the protocol buffer compiler.  DO NOT EDIT!#// Copyright (c) [2013-2014] Western Digital Technologies, Inc. All rights reserved.#g' $1/$2.pb.cc
sed -i 's|#include <algorithm>||g' $1/$2.pb.cc
sed -i 's|#include "'"$2"'.pb.h"||g' $1/$2.pb.cc
sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n#include <algorithm>\n#include <utility>\n#include "'"$2"'.pb.hpp"\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.cc
sed -i 's#switch(#switch (#g' $1/$2.pb.cc
sed -i 's#Kinetic.pb.h"#Kinetic.pb.hpp"#g' $1/$2.pb.cc
sed -i 's|   reinterpret_cast|  reinterpret_cast|g' $1/$2.pb.cc

#sed -i 's|&reinterpret_cast<Command|&(reinterpret_cast<Command|g' $1/$2.pb.cc
#sed -i 's|->f)|->f))|g' $1/$2.pb.cc

sed -i 's#// Generated by the protocol buffer compiler.  DO NOT EDIT!#// Copyright (c) [2013-2014] Western Digital Technologies, Inc. All rights reserved.#g' $1/$2.pb.h
sed -i 's#// namespace google#// namespace SHOULD_BE_protobuf#g' $1/$2.pb.h
sed -i 's#// namespace protobuf#// namespace SHOULD_BE_google#g' $1/$2.pb.h
sed -i 's#// namespace SHOULD_BE_protobuf#// namespace protobuf#g' $1/$2.pb.h
sed -i 's#// namespace SHOULD_BE_google#// namespace google#g' $1/$2.pb.h
sed -i 's|#include <string>||g' $1/$2.pb.h
if [ "$2" == "Entry" ]; then
    sed -i 's|#include "Kinetic.pb.h"||g' $1/$2.pb.h
    sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n#include "Kinetic.pb.hpp"\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.h
else
    sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.h
fi
mv $1/$2.pb.cc $1/$2.pb.cpp
mv $1/$2.pb.h $1/$2.pb.hpp

