#!/bin/sh
# Copyright (c) 2014-2016 Western Digital Technologies, Inc. <copyrightagent@wdc.com>
# 
# SPDX-License-Identifier: GPL-2.0+
# This file is part of Kinetic Advanced Object Store (KAOS).
# 
# This program is free software: you may copy, redistribute and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program; if
# not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA. <http://www.gnu.org/licenses/>

### BEGIN INIT INFO
# Provides:          kaos
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Kinetic daemon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=kaos
DAEMON=/usr/sbin/"$NAME"
PIDFILE=/var/run/"$NAME".pid

. /lib/lsb/init-functions
. /etc/default/kaos

case "$1" in
start)
        log_daemon_msg "Starting Kinetic daemon" "$NAME"
        start_daemon -p $PIDFILE $DAEMON
        log_end_msg $?
	;;
stop)
        log_daemon_msg "Stopping Kinetic daemon" "$NAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
        ;;
restart | force-reload)
        log_daemon_msg "Restarting Kinetic daemon" "$NAME"
        $0 stop
        $0 start
        ;;
clean-restart)
        log_daemon_msg "Cleanly Restarting Kinetic daemon" "$NAME"
        $0 stop
	rm -rf $ROOT_STORAGE_DIRECTORY/objectDatabase
	rm -rf $ROOT_STORAGE_DIRECTORY/serverSettings
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)
        log_action_msg "Usage: $0 {start|stop|restart|clean-restart|force-reload|status}"
        exit 2
        ;;
esac
exit 0
