#!/bin/bash
# Copyright (c) 2014-2016 Western Digital Corporation or its affiliates <copyrightagent@wdc.com>
#
# SPDX-License-Identifier: GPL-2.0+
# This file is part of Kinetic Advanced Object Store (KAOS).
#
# This program is free software: you may copy, redistribute and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program; if
# not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA. <http://www.gnu.org/licenses/>

# Fix the warning in the source file and rename it to have a cpp extension
sed -i 's#// Generated by the protocol buffer compiler.  DO NOT EDIT!#// Generated by the protocol buffer compiler (edited to eliminate cpplint warnings)#g' $1/$2.pb.cc
sed -i 's|#include <algorithm>||g' $1/$2.pb.cc
sed -i 's|#include "'"$2"'.pb.h"||g' $1/$2.pb.cc
sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n#include <algorithm>\n#include <utility>\n#include "'"$2"'.pb.hpp"\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.cc
sed -i 's#switch(#switch (#g' $1/$2.pb.cc
sed -i 's#Kinetic.pb.h"#Kinetic.pb.hpp"#g' $1/$2.pb.cc
sed -i 's|   reinterpret_cast|  reinterpret_cast|g' $1/$2.pb.cc
mv $1/$2.pb.cc $1/$2.pb.cpp

# Fix the warning in the include file and rename it to have a hpp extension
sed -i 's#// Generated by the protocol buffer compiler.  DO NOT EDIT!#// Generated by the protocol buffer compiler (edited to eliminate cpplint warnings)#g' $1/$2.pb.h
sed -i 's#// namespace google#// namespace SHOULD_BE_protobuf#g' $1/$2.pb.h
sed -i 's#// namespace protobuf#// namespace SHOULD_BE_google#g' $1/$2.pb.h
sed -i 's#// namespace SHOULD_BE_protobuf#// namespace protobuf#g' $1/$2.pb.h
sed -i 's#// namespace SHOULD_BE_google#// namespace google#g' $1/$2.pb.h
sed -i 's|#include <string>||g' $1/$2.pb.h
if [ "$2" == "Entry" ]; then
    sed -i 's|#include "Kinetic.pb.h"||g' $1/$2.pb.h
    sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n#include "Kinetic.pb.hpp"\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.h
else
    sed -i 's|// @@protoc_insertion_point(includes)|#include <string>\n// @@protoc_insertion_point(includes)|g' $1/$2.pb.h
fi
mv $1/$2.pb.h $1/$2.pb.hpp

